//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoz_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialManagement
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public decimal AllocatedAmount { get; set; }
        public decimal SpentAmount { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
