//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoz_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartupCapital
    {
        public int StartupID { get; set; }
        public decimal Amount { get; set; }
    }
}
