//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoz_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvents
    {
        public int UserEventID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Status { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Events Events1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
